const meetingConfig = {
    CALLOVERVIEW: 'Call Overview',
    CUSTOMERINFO: 'Customer Info',
    STATISTICS: 'Statistics',
    QUESTIONS: 'Questions',
    ACTIONITEMS: 'Action Items',
    RAWTRANSCRIPT: 'Raw Transcript',
    COMMENTS: 'Comments',
    NOCOMMENTS: 'No Comments',
    LISTENLATER: 'Listen Later',
    ADDTOLIB: 'Add To Library',
    COMMENTICON: 'fa-comment',
    TABLEICON: 'fa-table',
    CALLNAME: 'Call Name',
    CALLDURATION: 'Call Duration',
    CALLTYPE: 'Call Type',
    MEDIUM: 'Medium',
    RECEPIENTS: 'Recepients',
    AGENDA: 'Call Agenda',
    TAGS: 'Tags',
    NOAPPLIEDTAGS: 'No Applied Tags',
    TRACKERS: 'Trackers',
    APPLIED: 'Matching Trackers',
    NOMATCHINGTRACKERS: 'No Matching Trackers...',
    TRACKERICON: 'fa-newspaper-o',
    COMPLETED_TYPE: 'completed',
    UPCOMING_TYPE: 'upcoming',
    REPLYTOCOMMENT: 'Reply To Comment',
    REPLYICON: 'fa-commenting',
    ADDCOMMENT: 'Add Comment',
    ENTERCOMMENT: 'Enter the Comment',
    ADDTAG: 'Add a Tag',
    CANCEL: 'Cancel',
    REPLY: 'Reply',
    SEARCH: 'Search for a Word or Keyword',
    NOCALLTYPE: 'No Call Type',
    FEEDBACK: {
        label: 'Feedback',
        question_label: 'Question',
        your_response: 'Your Response',
        response: 'Response',
        scaleNumber: 10,
        scaleTrue: 'Yes',
        scaleFalse: 'No',
        addNoteBtn: 'Add Note',
        ratings: 'Ratings',
        responseScale: 1,
        responseBoolean: 2,
        AUTOSAVE_DURATION: 500,
        NOTES_NAME: 'note',
        NOTES_PLACEHOLDER: 'Write a note',
        IS_SAVING: 'saving...',
        feedbackBy: 'feedbackby',
        feedbackByTitle: 'Showing Feedback By:',
        NOTES: 'Notes',
        NO_NOTES: 'No notes yet',
        LABEL_YES: 'Yes',
        LABEL_NO: 'No',
        SHOW_NOTES: 'Show Notes',
    },

    // Video Player Constants
    PLAYRATES: [0.25, 0.5, 1, 1.25, 1.5, 2],
    SKIPBACKWARD: 'Skip 10 Seconds Backward',
    SKIPFORWARD: 'Skip 10 Seconds Forward',
    PLAY: 'Play',
    PAUSE: 'Pause',
    MUTE: 'Mute',
    UNMUTE: 'Unmute',
    SPEEDOPTIONS: 'Speed Options',
    LOOP: 'Loop',
    NOLOOP: 'Unloop',

    // Call Overview Section

    BUSINESSOVERVIEW: 'Business Overview',
    WHATWEDO: 'What We Do',
    LIBRARY: 'Library',
    OBJECTIONS: 'Objections',
    PRICING: 'Pricing',
    COACHING: 'Coaching',
    CALLER: 'Caller',
    RECEIVER: 'Receiver',
    TOPICS: 'Topics',
    LEGENDS: 'Legends',
    MAXTIMESTOPS: 10,
    AUTOSAVEDURATION: 500,
    QUESTIONTYPE: 'question',
    COMMENTTYPE: 'comment',
    KEYWORDTYPE: 'keyword',
    MAXTIMEBARS: 300,

    // Stats Section

    PATIENCE: 'Patience',
    TALKRATIO: 'Talk Ratio',
    QUESTION_RATE: 'Question Rate',
    INTERACTIVITY: 'Interactivity',
    LONGESTMONO: 'Longest Rep Monologue',
    LONGESTSTORY: 'Longest Customer Story',
    STATS_UNIT: ' MIN',

    // Call Transcript Section

    NOTRANSCRIPT: 'Transcripts Not Available.',
    NOTOPICS: 'No Topics Detected',

    // Question and Active Items Section
    ASKEDBYREPTYPE: 'askedbyrep',
    ASKEDBYOTHERSTYPE: 'askedbyothers',
    SAIDBYREPTYPE: 'saidbyrep',
    SAIDBYOTHERSTYPE: 'saidbyothers',
    NOACTIONITEMS: 'No Action Items.',
    NOQUESTIONS: 'No Questions Available.',
    ASKEDBYLABEL: 'Asked By:',
    ASKEDBYOTHERS: 'Asked By Other Parties',
    SAIDBYREP: 'Said By Rep',
    SAIDBY: 'Said By:',
    SAIDBYOTHERS: 'Said By Other Parties',
    SPEAKER_REP: 'owner',
    SPEAKER_CLIENT: 'client',

    MODAL: {
        TITLE: 'Add to library',
        BTN: 'add',
    },

    MERGE_THRESHOLD: 60,
};

export default meetingConfig;
